---
- name: Check Grafana admin password marker
  ansible.builtin.stat:
    path: /var/lib/grafana/.admin_password_set
  register: grafana_admin_marker

- name: Set Grafana admin password
  ansible.builtin.command: >
    grafana-cli admin reset-admin-password {{ grafana_admin_password }}
  register: grafana_admin_reset
  changed_when: grafana_admin_reset.rc == 0
  when:
    - grafana_admin_password | length > 0
    - not grafana_admin_marker.stat.exists

- name: Create Grafana admin password marker
  ansible.builtin.file:
    path: /var/lib/grafana/.admin_password_set
    state: touch
    mode: "0600"
  when:
    - grafana_admin_password | length > 0
    - not grafana_admin_marker.stat.exists
