---
- name: Install and configure Grafana
  ansible.builtin.include_tasks: grafana.yml

- name: Install and configure Nginx as reverse proxy
  ansible.builtin.include_tasks: nginx.yml

- name: Configure firewall with nftables (optional)
  ansible.builtin.include_tasks: firewall.yml
