apiVersion: 1

groups:
  - orgId: 1
    name: website-availability
    folder: Provisioned Alerts
    interval: 1m
    rules:
      - uid: cfdtg11sx1kowa
        title: <MONITORED_SITE> unavailable
        condition: A
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: prom_host01
            model:
              conditions:
                - evaluator:
                    params:
                      - 1
                    type: lt
                  operator:
                    type: and
                  query:
                    params:
                      - A
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: prometheus
                uid: prom_host01
              editorMode: code
              expr: probe_success{job="blackbox_exporter",instance="https://<MONITORED_SITE>"}
              hide: false
              instant: true
              interval: ""
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
              type: classic_conditions
        noDataState: Alerting
        execErrState: Alerting
        for: 5m
        keepFiringFor: 5m
        annotations:
          summary: Сайт <MONITORED_SITE> недоступен с точки наблюдения monitoring-server01
          description: Blackbox probe фиксирует probe_success < 1 в течение 5 минут для https://<MONITORED_SITE>
        labels:
          severity: critical
          site: <MONITORED_SITE>
        isPaused: false
